_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True]'
_last_obs:
    value: |-
        [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
         [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
         [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
         [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x7f6222fe8ad0>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 100000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.25.0
        e:
            l2mcx5xlfh9v990lm9decwsaamuooaok:
                args:
                    - --train
                    - --notes
                    - baeline model with 100k steps
                    - --timesteps
                    - "100000"
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "509943480320"
                        used: "419950223360"
                email: amanphankhu@gmail.com
                executable: /home/aman/projects/marl/.venv/bin/python
                git:
                    commit: d32e7226909ba85127853e935137b6e465fc6af3
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-5a787a1e-1ec9-db67-0d97-90f94db427e9
                host: alpha
                memory:
                    total: "16433549312"
                os: Linux-6.18.9-arch1-2-x86_64-with-glibc2.43
                program: -m src.smart_controller
                python: CPython 3.14.3
                root: /home/aman/projects/marl
                startedAt: "2026-02-27T06:29:39.439554Z"
                writerId: l2mcx5xlfh9v990lm9decwsaamuooaok
        m: []
        python_version: 3.14.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 16
                - 22
                - 35
            "4": 3.14.3
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Discrete(2)
algo:
    value: PPO
batch_size:
    value: 128
clip_range:
    value: 0.2
clip_range_vf:
    value: None
delta_time:
    value: 5
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x7f6251fdf8c0>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
max_grad_norm:
    value: 0.5
n_envs:
    value: 4
n_epochs:
    value: 10
n_steps:
    value: 512
normalize_advantage:
    value: "True"
num_envs:
    value: 4
num_timesteps:
    value: 0
observation_space:
    value: Box(0.0, inf, (10,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=10, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=10, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=2, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7f62502ef380>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1772173783714632165
switch_penalty:
    value: 2
target_kl:
    value: None
tensorboard_log:
    value: /home/aman/projects/marl/tb_logs
total_timesteps:
    value: 100000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
